#import "LUAPIModel.h"

/**
 Users may optionally choose to donate a percentage of their LevelUp savings to a cause of their choosing. When an
 order gets placed in which the user saved money, an `LUDonation` will be automatically generated by the platform.
 */
@class LUCause;
@class LUMonetaryValue;

@interface LUDonation : LUAPIModel

/**
 The cause to which the donation was made.
 */
@property (nonatomic, strong) LUCause *cause;

/**
 The amount of money which will be donated to the cause.
 */
@property (nonatomic, strong) LUMonetaryValue *value;

@end
